### ISSUE TITLE
Blocks without a corresponding held item are not properly handled.

### ISSUE THREAD

**Issue by Aaron1011** [EdificeMC/Edifice#1]
On [this line](https://github.com/RobertHerhold/Edifice/blob/master/src/main/java/me/reherhold/edifice/eventhandler/InteractEntityEventHandler.java#L188), the `HeldItemProperty` optional is unwrapped without being checked. However, not all blocks have a corresponding held item, even if they were placed in the world by an item. An example of this is `minecraft:lit_redstone_lamp`, which unlike `minecraft:redstone_lamp`, lacks an applicable `HeldItemProperty`.

This results in certain structures, such as Awesome Temple', being unable to be loaded by the plugin.

**Comment by RobertHerhold** [comment]
Thanks for reporting this - I've been working on fixing this on the bleeding/profusely-bleeding branches, as well as some other fixes

**Comment by RobertHerhold** [comment]
Resolved by 14a03126d9bea8dd10d01bf12a2350705f8ee787 and 35bc53a303121b8e09e849c3cbb608004e7834a1
